config/routes.rb
Rails.application.routes.draw do
  get 'books/new'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show' , as: 'book'
  get 'books/:id/edit' => 'books#edit' , as: 'edit_book'
  get '/books' => 'books#books'

  patch 'books/:id' => 'books#update' , as: 'update_book'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => 'homes#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def books
    @books = Book.all
    @book = Book.new

  end

  def new
      @book = Book.new
  end

  def create
    @books =Book.all
    @book = Book.new(book_params)

    if @book.save
       flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :books
    end
  end

  def show
      @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
       flash[:notice] = "Book was successfully created."

      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end


private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/books.html.erb
<!DOCTYPE html>
<html>
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to 'Show', "/books/#{book.id}" %></td>
        <td><%= link_to "Edit", "/books/#{book.id}/edit"%></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <h2>New Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
  <div class ="new-book">Title</div>
  <%= f.text_field :title %>

  <div class ="new-book">Body</div>
  <%= f.text_area :body %>

<div class="button"><%= f.submit '  Create Book  '%></div>

<% end %>

</html>

app/views/books/edit.html.erb
<!DOCTYPE html>
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

<div class="flash">
  <%= flash[:notice] %>
</div>
<div>Title</div>
<%= f.text_field :title %>

  <div>Body</div>
  <%= f.text_area :body %>

 <div class="button"> <%= f.submit '  Update Book  ' %></div>

 <%= link_to 'Show', "/books/#{@book.id}" %>
 | <%= link_to 'Back', '/books' %>



<% end %>

app/views/books/show.html.erb
<!DOCTYPE html>
<html>
<div class="flash">
  <%= flash[:notice] %>
</div>

<p><b>Title:</b> <%= @book.title %></p>

<p><b>Body:</b> <%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
| <%= link_to 'Back', '/books' %>

</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
  <body>
    <h1>ようこそ <strong>Bookers</strong> へ！</h1>
      <p><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や</p>
      <p>印象を共有し交換することができます</p>
<p><%= link_to 'start', '/books' %></P>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>WebCampBackendNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>